name: masareefk
description: A Masareefk App for Track Expense

publish_to: 'none'

version: 1.2.2+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization & UI
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5

  # database
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

  # Charts & Intl
  fl_chart: ^0.66.2
  intl: ^0.19.0

  # AI
  google_generative_ai: ^0.4.0

  # Connectivity & Sharing (Updated connectivity_plus)
  connectivity_plus: ^6.0.3
  share_plus: ^9.0.0

  # PDF & Printing
  pdf: ^3.11.0
  printing: ^5.12.0
  device_preview: ^1.1.0        # preview on different devices
  flutter_local_notifications: ^17.2.4
  flutter_timezone: ^4.1.1
  timezone: ^0.9.4
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  # Changed asset listing to include the whole folder for future scalability
  assets:
    - assets/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
